var timetable = {
    "a2": {
        "wood": 66,
        "perspex": 118,
        "anodized aluminum": 38,
        "leather": 66,
        "cardboard": 26,
        "paper": 27,
        "enamel rotary": "N/A",
        "glass flat": 16,
        "glass rotary": "N/A",
        "not-required": 0
    },
    "a3": {
        "wood": 33,
        "perspex": 59,
        "anodized aluminum": 19,
        "leather": 33,
        "cardboard": 13,
        "paper": 20,
        "enamel rotary": "N/A",
        "glass flat": 11,
        "glass rotary": "N/A",
        "not-required": 0
    },
    "a4": {
        "wood": 16,
        "perspex": 29,
        "anodized aluminum": 9,
        "leather": 17,
        "cardboard": 7,
        "paper": 10,
        "enamel rotary": "17",
        "glass flat": 6,
        "glass rotary": "13",
        "not-required": 0
    },
    "a5": {
        "wood": 8,
        "perspex": 15,
        "anodized aluminum": 5,
        "leather": 8,
        "cardboard": 3,
        "paper": 5,
        "enamel rotary": "9",
        "glass flat": 3,
        "glass rotary": "7",
        "not-required": 0
    },
    "a6": {
        "wood": 4,
        "perspex": 7,
        "anodized aluminum": 2,
        "leather": 4,
        "cardboard": 2,
        "paper": 3,
        "enamel rotary": "4",
        "glass flat": 1,
        "glass rotary": "3",
        "not-required": 0
    },
    "a7": {
        "wood": 2,
        "perspex": 4,
        "anodized aluminum": 1,
        "leather": 2,
        "cardboard": 1,
        "paper": 1,
        "enamel rotary": "2",
        "glass flat": 1,
        "glass rotary": "2",
        "not-required": 0
    },
    "a8": {
        "wood": 1.03,
        "perspex": 1.84,
        "anodized aluminum": 0.59,
        "leather": 1.03,
        "cardboard": 0.41,
        "paper": 0.63,
        "enamel rotary": "1.06",
        "glass flat": 0.34,
        "glass rotary": "0.81",
        "not-required": 0
    },
    "a9": {
        "wood": 0.51,
        "perspex": 0.92,
        "anodized aluminum": 0.29,
        "leather": 0.52,
        "cardboard": 0.2,
        "paper": 0.32,
        "enamel rotary": "0.53",
        "glass flat": 0.17,
        "glass rotary": "0.41",
        "not-required": 0
    },
    "a10": {
        "wood": 0.257,
        "perspex": 0.459,
        "anodized aluminum": 0.146,
        "leather": 0.258,
        "cardboard": 0.102,
        "paper": 0.159,
        "enamel rotary": "0.266",
        "glass flat": 0.086,
        "glass rotary": "0.203",
        "not-required": 0
    },
    "30x30": {
        "wood": 3,
        "perspex": 2,
        "anodized aluminum": 2,
        "leather": 2,
        "cardboard": 2,
        "paper": 2,
        "enamel rotary": "2.00",
        "glass flat": 2,
        "glass rotary": "2.00",
        "not-required": 0
    },
    "25x30": {
        "wood": 2.7,
        "perspex": 1.8,
        "anodized aluminum": 1.8,
        "leather": 1.8,
        "cardboard": 1.8,
        "paper": 1.8,
        "enamel rotary": "1.8",
        "glass flat": 1.8,
        "glass rotary": "1.8",
        "not-required": 0
    },
    "25x25": {
        "wood": 2.4,
        "perspex": 1.6,
        "anodized aluminum": 1.6,
        "leather": 1.6,
        "cardboard": 1.6,
        "paper": 1.6,
        "enamel rotary": "1.6",
        "glass flat": 1.6,
        "glass rotary": "1.6",
        "not-required": 0
    },
    "20x25": {
        "wood": 2.1,
        "perspex": 1.4,
        "anodized aluminum": 1.4,
        "leather": 1.4,
        "cardboard": 1.4,
        "paper": 1.4,
        "enamel rotary": "1.4",
        "glass flat": 1.4,
        "glass rotary": "1.4",
        "not-required": 0
    },
    "20x20": {
        "wood": 1.98,
        "perspex": 1.32,
        "anodized aluminum": 1.32,
        "leather": 1.32,
        "cardboard": 1.32,
        "paper": 1.32,
        "enamel rotary": "1.32",
        "glass flat": 1.32,
        "glass rotary": "1.32",
        "not-required": 0
    },
    "15x20": {
        "wood": 1.65,
        "perspex": 1.1,
        "anodized aluminum": 1.1,
        "leather": 1.1,
        "cardboard": 1.1,
        "paper": 1.1,
        "enamel rotary": "1.1",
        "glass flat": 1.1,
        "glass rotary": "1.1",
        "not-required": 0
    },
    "15x15": {
        "wood": 1.5,
        "perspex": 1,
        "anodized aluminum": 1,
        "leather": 1,
        "cardboard": 1,
        "paper": 1,
        "enamel rotary": "1.00",
        "glass flat": 1,
        "glass rotary": "1.00",
        "not-required": 0
    },
    "10x10": {
        "wood": 0.99,
        "perspex": 0.66,
        "anodized aluminum": 0.66,
        "leather": 0.66,
        "cardboard": 0.66,
        "paper": 0.66,
        "enamel rotary": "0.6600",
        "glass flat": 0.66,
        "glass rotary": "0.6600",
        "not-required": 0
    },
    "5x10": {
        "wood": 0.6,
        "perspex": 0.4,
        "anodized aluminum": 0.4,
        "leather": 0.4,
        "cardboard": 0.4,
        "paper": 0.4,
        "enamel rotary": "0.4000",
        "glass flat": 0.4,
        "glass rotary": "0.4000",
        "not-required": 0
    },
    "5x5": {
        "wood": 0.48,
        "perspex": 0.32,
        "anodized aluminum": 0.32,
        "leather": 0.32,
        "cardboard": 0.32,
        "paper": 0.32,
        "enamel rotary": "0.3200",
        "glass flat": 0.32,
        "glass rotary": "0.3200",
        "not-required": 0
    }
}